services:
  spectra:
    build: .
    container_name: spectra_hand_control
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
      - ./src:/app/src
    stdin_open: true
    tty: true
    network_mode: host

